### ISSUE TITLE
RuntimeError: all tensors must be on devices[0] when training with multiple GPUs

### ISSUE THREAD

**Issue by jinxiazhangchina** [WXinlong/SOLO#4]
Hello, I successfully installed the soso based on mmdet v1.0.0 and compiled well.
I can train the model with 1 GPU.
However, the runtime error occurs when I try to train the model with multiple GPUs.

The error looks like:
return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: all tensors must be on devices[0]
return comm.broadcast_coalesced(tensors, devices)

The script I am using is : ./tools/dist_train.sh configs/solo/solo_r50_fpn_8gpu_1x.py  8
The dataset  I used is coco2017

**Environment**
sys.platform: linux
Python: 3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
CUDA available: True
GCC: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.4.2
MMDetection: 1.0.0+unknown
MMDetection Compiler: GCC 8.2
MMDetection CUDA Compiler: 10.1

**Comment by zzzzzz0407** [comment]
degrade mmcv==0.2.16 
**OR** 
replace the code in mmdet/apis/train.py Line 208
``
    # put model on gpus
    model = MMDistributedDataParallel(model.cuda())
``
with
``
    # put model on gpus
    model = MMDistributedDataParallel(model.cuda(),
                   device_ids=[torch.cuda.current_device()],
                   broadcast_buffers=False)
``

**Comment by taokong** [comment]
@jinxiazhangchina using mmcv==0.2.16 should resolve this issue.

**Comment by jinxiazhangchina** [comment]
Thanks a lot for your reply. First I degraded mmcv==0.4.0, it seems this error still occurs. Then I degraded mmcv==0.2.16, it works!
